### ISSUE TITLE
How about Core temperature

### ISSUE THREAD

**Issue by smartshogu** [shevabam/ezservermonitor-web#10]
Thanks for the last update - favicon looks nice ;)

A core temperature read out in the CPU-panel would be nice
or a separate/coloured temperature panel would be awesome 

Have a nice day!

**Comment by veka-server** [comment]
i make it for me, if you like it, you could take it.
https://github.com/veka-server/ezservermonitor-web

**Comment by shevabam** [comment]
Just add the CPU temp.

You can enable or disable it in the conf/esm.config.json file (cpu section).
