### ISSUE TITLE
False line endings in esm.config.json - generated ParserError (give 500 error in browsers)

### ISSUE THREAD

**Issue by MirkoBrunner** [shevabam/ezservermonitor-web#18]
The config.json has CRLF (Microsoft) line endings but it should only have CR for Linux and/or Mac servers.

**Comment by shevabam** [comment]
I do not have this error.
When I switch the files in Unix format, I have nothing to commit :/

**Comment by MirkoBrunner** [comment]
All right. I will describe it in a little more detail. Could this be the error was only with me.

I have downloaded the zip today and put the folder on my Sever (Debian 7.8). And have a white page in my browser. On the (browser) console i can see a 500 Server error. In my logs i can see this line:
    
    PHP Fatal error:  Uncaught exception 'LogicException' with message 'Failed to parse config file 'esm.config.json'. Error: 'Syntax error'' in /var/www/dock/monitor/libs/Utils/Config.class.php:27\nStack trace:\n#0 /var/www/dock/monitor/libs/Utils/Config.class.php(17): Config->_readFile()\n#1 /var/www/dock/monitor/index.php(4): Config->__construct()\n#2 {main}\n  thrown in /var/www/dock/monitor/libs/Utils/Config.class.php on line 27
    
Note: I have not edited the file. And work under OSX.

**Comment by MirkoBrunner** [comment]
OK i think this is a git-config think ;) but i am not a expert in git. i found this on stackoverflow. hope it help´s
http://stackoverflow.com/questions/10418975/how-to-change-line-ending-settings

**Comment by shevabam** [comment]
Thanks for the URL but it doesn't change anything :( 

Can you change the line endings format on your side ?
Can you paste your esm.config.json file content (here or pastebin) ? I know you have nothing changed, but I am just checking ;)
