### ISSUE TITLE
Wrong disk usage

### ISSUE THREAD

**Issue by Micht69** [shevabam/ezservermonitor-web#2]
Hi,

The disk usage has some boggus values because I'm using LVM.
First, I had to change the tail command from "tail -n +2" to "tail -n +3" but even after that, the display is wrong :
![disk_usage](https://cloud.githubusercontent.com/assets/2040345/3824584/55ee3120-1d49-11e4-9007-05917bca7b5f.png)

Here is the result of df command :
![df_result](https://cloud.githubusercontent.com/assets/2040345/3824594/6fe220a0-1d49-11e4-8fcb-d87e2d2f0125.png)

The problem is caused by the "/" mount point having no name ...

Thanks

EDIT : My bad, the problem layed in the df command ... the name of the / mount is displayed on a separate line.

**Comment by Albirew** [comment]
Latest 2.5 release reintroduced the "space in cifs drive" bug. Wonder if I have to make a new issue or just commenting on this one is fine.

**Comment by shevabam** [comment]
Yes, please open a new issue, it will be more understandable ;)
