### ISSUE TITLE
Displaying SMART data 

### ISSUE THREAD

**Issue by thegounet** [shevabam/ezservermonitor-web#22]
I just download the new 2.5 version. 
So, I have a suggestion. Why do not display SMART data like disk temperature ? 

thank for your work

**Comment by shevabam** [comment]
Thank you for the suggestion ;)
It's interesting but the hard drive temperature is obtained with smartctl or hddtemp. But, the objective of eSM`Web is precisely to be able to work without installing additional package.

However, I keep the suggestion!
