### ISSUE TITLE
Error 404 Not Found

### ISSUE THREAD

**Issue by T1tin** [shevabam/ezservermonitor-web#24]
Hi!
I followed the installation protocol, but when I go to http: // {my-ip} / eZServerMonitor I get a 404 error.
Someone to help me?
Thank you

**Comment by Wohlraj** [comment]
Have you configured your web server (e.g. Apache) to point to the directory of ezservermonitor?

**Comment by T1tin** [comment]
Thank you for your reply but I used Nginx web server.
But I remade my setup with apache and it's good now.
Thank you
