### ISSUE TITLE
PHP timezone warning 

### ISSUE THREAD

**Issue by sodz** [shevabam/ezservermonitor-web#26]
PHP adds a warning message before the system info JSON, making the `System` section unable to display.

<b>Warning</b>:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in <b>/path/to/ezservermonitor-web/libs/system.php</b> on line <b>45</b><br />

**Comment by shevabam** [comment]
Hello,

Yes, you have to set the default timezone in php.ini file (ex: date.timezone = Europe/Paris).

**Comment by sodz** [comment]
Hi, Thanks for your reply. You are right, I forgot to set the default timezone. But I think it might be a good idea to use `date_default_timezone_set()` in the script in order for it to work out of the box.

**Comment by shevabam** [comment]
Yes, you're right ;)

Changed here : https://github.com/shevabam/ezservermonitor-web/commit/30db2217136c5b64845a1104e4f5fbea4badf0bd
