### ISSUE TITLE
Truncated /bin/df gives 0

### ISSUE THREAD

**Issue by awsumco** [shevabam/ezservermonitor-web#27]
Great work here but found that if disk mounts have long names, the case of LVM's the output is zero. 

In order to fix the correct output I add '--portability' to the df command in disk.php.

From Man Page:

`-P'
`--portability'
     Use the POSIX output format.  This is like the default format
     except for the following:

       1. The information about each filesystem is always printed on
          exactly one line; a mount device is never put on a line by
          itself.  This means that if the mount device name is more
          than 20 characters long (e.g., for some network mounts), the
          columns are misaligned.

       2. The labels in the header output line are changed to conform
          to POSIX.

**Comment by shevabam** [comment]
Hello,

Thanks ! I made the change on the file ;)
