### ISSUE TITLE
Ajax reload lot times is loading high CPU

### ISSUE THREAD

**Issue by joubertredrat** [shevabam/ezservermonitor-web#29]
Hi guys,

I'm testing web version of this and I liked a lot, but have one problem, If you press to ajax reload all widgets, causes high load avg on server, similar a DoS, then I think that is good idea to have flag to prevent this.

I tested this on my vps with htop on terminal and web and avg values is correct, then isn't web bug.

Thanks

**Comment by shevabam** [comment]
Hi,

Sorry but I can not reproduce the problem :/

**Comment by joubertredrat** [comment]
Hi @shevabam,

On a principal reload button, simple click a lot of times without wait response while top is opened on your vps
