### ISSUE TITLE
Historical data graphs

### ISSUE THREAD

**Issue by niutech** [shevabam/ezservermonitor-web#31]
Please provide graphs for historical data, like CPU and memory usage over the last minute/hour/day. The monitoring agent could keep running a [background process](https://github.com/cocur/background-process). To make it lightweight, it could use SQLite or a flat file database.

**Comment by shevabam** [comment]
Hi,

The goal of eZ Server Monitor is not to have graphics on the dashboard but to have a state of several datas at a specific time.
In addition, I really want to keep eZ Server Monitor the more lightest possible and easiest possible installation!
I agree that SQLite is very light but I really wish eZ Server Monitor as simple as possible!

However, there is other projects that will do what you ask ;)

Thanks ;)

**Comment by niutech** [comment]
Which other lightweight projects do you recommend?

**Comment by shevabam** [comment]
You have : 
- linux-dash (https://github.com/afaqurk/linux-dash)
- munin (http://munin-monitoring.org/)
- monit (https://mmonit.com/monit/)
- librenms (http://www.librenms.org/)

**Comment by niutech** [comment]
Thank you.
