### ISSUE TITLE
Feature req: Show S.M.A.R.T statuses?

### ISSUE THREAD

**Issue by kodapaio** [shevabam/ezservermonitor-web#32]
Hi!

Is there some way to show S.M.A.R.T statuses on the page in the feature?

Best
Pontus

**Comment by shevabam** [comment]
Hi !

eZ Server Monitor is meant to be simple, whether in appearance, in usage, but especially in the installation.
To have the SMART statuses, you have to install the package smartctl. And given that eZ Server Monitor should be simple to install, I do not think that SMART statuses will be on eSM.
