### ISSUE TITLE
Ubuntu 16.04 support

### ISSUE THREAD

**Issue by mmolitor87** [shevabam/ezservermonitor-web#35]
I just upgraded from 14.04 to 16.04 tonight and realized that ESM doesn't seem to load on it. I'm greeted with a completely blank page.

At first I thought it must be php7.4 that is packaged with 16.04, so I removed it and added php5.6 through a repository, with no changes.

I have grown quite attached to using this page as a quick monitoring tool and am curious how I can help to expedite support!

**Comment by shevabam** [comment]
Hi,

Try to install php-xml (apt-get install php-xml).

**Comment by mmolitor87** [comment]
That definitely worked. Not sure how I  missed that!

**Comment by shevabam** [comment]
Good!

I only turn on PHP errors and utf8_decode() function was not available. A brief search showed me that with PHP7, you had to install php-xml !

**Comment by mmolitor87** [comment]
I appreciate it. I really love how simple and yet information ESM is. :)
