### ISSUE TITLE
network mount point

### ISSUE THREAD

**Issue by fab76** [shevabam/ezservermonitor-web#36]
Hi, It's a very good web interface, but I've a little problem.
The network mounts are not displayed.
Is it possible to display the network mount on diskusage?
ex : //192.168.1.1/nas mounted on /mnt/nas/ ?

Thanks

**Comment by Wohlraj** [comment]
It works for me. can you show the output of `/bin/df -T -H`?

**Comment by fab76** [comment]
thanks to your answer :+1: 
/dev/root                          ext4       3,8G    2,0G  1,7G  55% /
devtmpfs                           devtmpfs   224M       0  224M   0% /dev
tmpfs                              tmpfs      228M       0  228M   0% /dev/shm
tmpfs                              tmpfs      228M    8,8M  220M   4% /run
tmpfs                              tmpfs      5,3M    4,1k  5,3M   1% /run/lock
tmpfs                              tmpfs      228M       0  228M   0% /sys/fs/cgroup
/dev/mmcblk0p1                     vfat        67M     22M   45M  33% /boot
//192.168.0.32/volume_1            cifs       2,0T    1,5T  470G  77% /mnt/nas
//mafreebox.freebox.fr/disque dur/ cifs       245G    166G   68G  72% /mnt/freebox

**Comment by Wohlraj** [comment]
Sorry, this is not enough for me to understand the problem :(
Can you try this one: `/bin/df -T -P | sed -e 's/[ \t]//' |  awk -v c=`/bin/df -T | grep -bo "Type" | awk -F: '{print $2}'` '{print substr($0,c);}'`
See, the command `sed -e 's/[ \t]//'` was added to allow Freebox users to see the 'disque dur' which has a space in the name. But it may cause trouble in some particular case, like there is only one space between the 'Filesystem' and the 'Type' columns of the above command: then the two columns get mixed up and nothing works anymore.

**Comment by shevabam** [comment]
Hi,

There is an option in file config (conf/esm.config.json).
Check if **disk:show_filesystem** is **true**

I have a Freebox and I try this (I just added the "sed -e" part) : 

`/bin/df -T -P | sed -e 's/[ \t]//' | awk -v c=`/bin/df -T | grep -bo "Type" | awk -F: '{print $2}'` '{print substr($0,c);}' | tail -n +2 | awk '{print $1","$2","$3","$4","$5","$6","$7}'`

It returns : 

`//192.168.1.254/Disquedur,cifs,239216092,86063064,140978444,38%,/mnt/freebox`

Before : 

`//192.168.1.254/Disque,dur,cifs,239216092,86063064,140978444,38%`

So, it could fix the problem ;)
