### ISSUE TITLE
iperf3 Bandwidth Test Module?

### ISSUE THREAD

**Issue by benyanke** [shevabam/ezservermonitor-web#41]
If I write a module which used iperf3 to test the bandwidth from the server to a remote server, would you take pull request?

**Comment by shevabam** [comment]
Hi !

eZ Server Monitor is meant to be simple, whether in appearance, in usage, but especially in the installation.
To have the iperf results, you have to install a package. I really want to keep eZ Server Monitor the more lightest possible and easiest possible installation! Everything must run after installation!

**Comment by benyanke** [comment]
Fair enough, I certainly respect that goal. That's partly what brought me to it. Fork time!

Perhaps... "benyanke/SomewhatEzServerMonitor"

;)

And of course, if I find a way with PHP do to a bandwidth test using almost-always-installed libraries, I'll certainly write it up and PR!
