### ISSUE TITLE
Major CSS code issues

### ISSUE THREAD

**Issue by RheaAyase** [shevabam/ezservermonitor-web#44]
Long story short, the whole CSS is formatting whole tags instead of using classes.

This for example enforces `<a>` tag to be formatted with `display: inline-block;` instead of correctly inheriting the parent, etc etc...

**Comment by shevabam** [comment]
Can you give me a specific example?

_It's an open source amateur project, and I owe you nothing. If you noticed something that was wrong, you can do a PR, with a detailed report._
