### ISSUE TITLE
Mobile view of "Load Average" panel does not show correctly

### ISSUE THREAD

**Issue by dustindauncey** [shevabam/ezservermonitor-web#5]
The view of the Load panel in the upper-most-right corner does not load as expected when viewing on a mobile device. 

Example: I have an iPhone 5S and the numbers beneath the graphs do not show as they should. Not sure how to fix this yet so until I can figure it out I at least wanted to report it. Images attached for reference. 

![](http://i.imgur.com/vsLgXW4.jpg)
![](http://i.imgur.com/qb3qaZh.jpg)

**Comment by shevabam** [comment]
I modified the CSS to consider the responsive design.
