### ISSUE TITLE
Sequence of CPU load from mobile

### ISSUE THREAD

**Issue by protik77** [shevabam/ezservermonitor-web#57]
The sequence of CPU load from mobile seems to be 1 min, 15 min and 5 min which is different from what seen on a desktop browser. I tried both Chrome and Firefox on Android. In the desktop, the sequence is 1 min, 5 min and 15 min which makes more sense.

Example: [Screenshot hosted in Imgur](https://imgur.com/a/CS0GG).

**Comment by shevabam** [comment]
Fixed!
Thanks!
