### ISSUE TITLE
Exclude devices from disk view

### ISSUE THREAD

**Issue by nowthatscool** [shevabam/ezservermonitor-web#60]
I've been using esm for quite some time now and it's been really handy. Last week I upgrade to Ubuntu 18.04 and set up Canonical Live Patching. This required me to install snapd. Now snapd has made some virutual disks called /dev/loop0 /dev/loop1 etc. How can I exclude these from displaying in esm?
![diskusage](https://user-images.githubusercontent.com/38328038/40230329-08f6366a-5a8f-11e8-9f6b-10da898b8bfe.png)

**Comment by HBadertscher** [comment]
You can add the devices to the `ignore_mounts` option in your config file `conf/esm.config.json`. Your `"disk"` section will then look e.g. like this:
```
"disk": {
    "show_tmpfs": false,
    "show_filesystem": true
    "ignore_mounts": ["/dev/loop0", "/dev/loop1", "/dev/loop2"]
},
```
However this requires you to add all loop devices to that option manually. I think it should be possible to extend the `"ignore_mounts"` option to allow for excluding disks using a regexp. I'll try to look into this and might create a pull request.

**Comment by shevabam** [comment]
Hi!

Thanks for your feedback!

I added an option (disk / show_loop) in the configuration file (conf/esm.config.json) to allow or not the display of /dev/loopX.
By default, this will not be displayed (false).

**Comment by nowthatscool** [comment]
Sorry for the late reply, but thank you very much for fixing this!
