### ISSUE TITLE
PHP Notice:  A non well formed numeric value

### ISSUE THREAD

**Issue by zastavra** [shevabam/ezservermonitor-web#64]
Hi,

I'm getting this in nginx log.

`PHP message: PHP Notice:  A non well formed numeric value encountered in /home/www/ezservermonitor/libs/swap.php on line 22
PHP message: PHP Notice:  A non well formed numeric value encountered in /home/www/ezservermonitor/libs/swap.php on line 27
PHP message: PHP Notice:  A non well formed numeric value encountered in /home/www/ezservermonitor/libs/swap.php on line 28" while reading response header from upstream, client: 2.85.5.141, server: domain.com, request: "GET /ezservermonitor/libs/swap.php HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "domain.com",`

**Comment by franko108** [comment]
Hi, 
on newer PHP version (my is 7.3 on Apache) is the same error. Apparently, integer must be explicitly marked.
I've put in ~/libs/load_average.php, line 16:

>$value = (int)$value;
>$cores  = (int)$cores;


The same in memory.php on line 22
>$total = (int)$total;
 >$free = (int)$free;

then in swap.php and Misc.php.
Then it works properly.

However, on Debian, **ifconfig** command required to be root, something as **ip a** could be a better, newer solution.

**Comment by shevabam** [comment]
Thank you for your report.

Are you testing on the version 2.5 of eZ Server Monitor, the one available on the site or via the "master" branch of the Github repository?

The Github repository contains several updates compared to version 2.5, available on the site.

You can see that these problems are fixed:

memory.php:

https://github.com/shevabam/ezservermonitor-web/blob/a66bd8f49d3fe9c31724d55623a2e7ee2ba152bb/libs/memory.php#L12

https://github.com/shevabam/ezservermonitor-web/blob/a66bd8f49d3fe9c31724d55623a2e7ee2ba152bb/libs/memory.php#L20

load_average.php:

https://github.com/shevabam/ezservermonitor-web/blob/a66bd8f49d3fe9c31724d55623a2e7ee2ba152bb/libs/load_average.php#L17

**Comment by franko108** [comment]
Yes, I've took latest version from github in order to make a pull request, but it is fixed, as you said. :-) 
It is working properly.
Errors are from version 2.5 from official page.

**Comment by shevabam** [comment]
Ok, thanks!
The next version should arrive soon, I hope!
