### ISSUE TITLE
Suggestion: add a live chart for CPU and RAM usage

### ISSUE THREAD

**Issue by saudiqbal** [shevabam/ezservermonitor-web#67]
Similar to this one https://github.com/MichaelBelgium/VPS-Monitor

**Comment by mcunha98** [comment]
I  agree with you, I'm back here to write it, give a suggestion to add historiacal chart of consume (CPU/RAM/NETWORK), it will really amazing for this dashboard

**Comment by shevabam** [comment]
Hello,
Thank you for the suggestion which is interesting but eSM is not intended to integrate graphs. eSM is a very simple approach tool intended to be as simple as possible for the user to set up.
