### ISSUE TITLE
Floating point error? Possibly?

### ISSUE THREAD

**Issue by hariseldon99** [shevabam/ezservermonitor-web#74]
I'm not much of a php guy, but the lighttpd error log keeps showing this error:

 (mod_fastcgi.c.2543) FastCGI-stderr: PHP Notice:  A non well formed numeric value encountered in /var/www/ ... /ezservermonitor/libs/memory.php on line 27

Line 27 on memory.php is:

// Percent used
$percent_used = 0;
if ($total > 0)
    $percent_used = 100 - (round($free / $total * 100));

Assuming that floating point arithmetic works on php just like any high level dynamically typed programming language, this looks right. So what seems to be the problem???

**Comment by shevabam** [comment]
Hi,
It's fixed on the code present in this repository.
Thanks!
